services:
  wordpress:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - $PWD/www:/var/www/html
      - $PWD/wordpress/config/maildev.ini:/usr/local/etc/php/conf.d/maildev.ini
    userns_mode: "keep-id:uid=33,gid=33"
    user: "root"
    networks:
      - backnet
      - reverse-proxied

  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - $PWD/db.env
    secrets:
      - mysql_root_password
      - mysql_haribol_password
    networks:
      - backnet

  adminer:
    image: adminer:5
    restart: unless-stopped
    networks:
      - backnet
      - reverse-proxied

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
    networks:
      - backnet
      - reverse-proxied

volumes:
  mysql-data:


secrets:
  mysql_root_password:
    file: $PWD/secrets/mysql_root_password
  mysql_haribol_password:
    file: $PWD/secrets/mysql_haribol_password

networks:
  backnet:
  reverse-proxied:
    external: true
