services:
  wordpress:
    build: ./wordpress
    volumes:
      - $PWD/www:/var/www/html
      - $PWD/wordpress/config/maildev.ini:/usr/local/etc/php/conf.d/maildev.ini
    userns_mode: "keep-id:uid=33,gid=33"
    user: "root"
    networks:
      - backnet
      - reverse-proxied

  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - $PWD/db.env
    secrets:
      - mysql_root_password
      - mysql_haribol_password
    networks:
      - backnet

  adminer:
    image: adminer:5
    restart: unless-stopped
    networks:
      - backnet
      - reverse-proxied

  maildev:
    image: maildev/maildev
    networks:
      - backnet
      - reverse-proxied

  reverse-proxy:
    image: caddy:2
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/reverse-proxy/conf/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8443:8443/udp"
    networks:
      - reverse-proxied
    secrets:
      - localhost.crt
      - localhost.key

volumes:
  mysql-data:
  caddy_data:
  caddy_config:

secrets:
  localhost.crt:
    external: true
  localhost.key:
    external: true
  mysql_root_password:
    file: $PWD/secrets/mysql_root_password
  mysql_haribol_password:
    file: $PWD/secrets/mysql_haribol_password

networks:
  backnet:
  reverse-proxied:
