services:
  wordpress:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - $PWD/www:/var/www/html
    userns_mode: "keep-id:uid=33,gid=33"
    user: "root"
    networks:
      - backnet
      - reverse-proxied

  db:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    env_file:
      - $PWD/db.env
    secrets:
      - mysql_root_password
      - mysql_haribol_password
    networks:
      - backnet

  adminer:
    image: adminer:5
    restart: unless-stopped
    networks:
      - backnet
      - reverse-proxied

volumes:
  mariadb-data:


secrets:
  mysql_root_password:
    file: $PWD/secrets/mysql_root_password
  mysql_haribol_password:
    file: $PWD/secrets/mysql_haribol_password

networks:
  backnet:
  reverse-proxied:
    external: true
