#!/bin/sh

COMPOSE_CMD="podman-compose";

${COMPOSE_CMD} pull \
  && ${COMPOSE_CMD} build --pull \
  && ${COMPOSE_CMD} up --remove-orphans;
${COMPOSE_CMD} down --remove-orphans; # Automatically cleanup after 'up'